
import { advertLoadedSuccess, authLogin } from '../actions';


describe('Testing React Redux actions', () => {
    var dispatch;
    var getState;
    var service = {};
    var router;
    var auth;
    describe('Testing React Redux ASYNC action "authLogin"', () => {
        beforeEach(() => {
            dispatch = jest.fn(); //Create a dispatch false function
            getState = jest.fn(); //Create a getState false function
            router = { navigate: jest.fn() }; //Create a false router
            auth = {
                login: jest.fn(),
            };
        });

        afterEach(() => {
            jest.restoreAllMocks();
        });

        //Testing login success

        test('"authLogin" dispatches "authLoginSuccess" & navigates to "/" when login is succeess', async () => {
            auth.login.mockResolvedValue({
                success: true,
                user: {
                    email: 'test@test.com',
                    password: '1234',
                },
            });
            const credentials = {
                email: 'test@test.com',
                password: '1234',
            };
            //Expected dispatched actions
            const expectedActions = [
                { type: 'AUTH_LOGIN_REQUEST' },
                { type: 'AUTH_LOGIN_SUCCESS' },
            ];
            //Dispatch the async action and wait for it to be resolved.
            await authLogin(credentials)(dispatch, getState, {
                service: { auth },
                router,
            });

            //Check that dispatched actions are as expected.
            expect(dispatch).toHaveBeenCalledTimes(2);
            expect(dispatch).toHaveBeenNthCalledWith(1, expectedActions[0]);
            expect(dispatch).toHaveBeenNthCalledWith(2, expectedActions[1]);

            // Comprobar que se ha navegado a la ruta /
            expect(router.navigate).toHaveBeenCalledWith('/');
        });
        test('authLogin dispatches "authLoginFailure" and throws error when login fails', async () => {
            // Make the authLogin function return a rejected promise with an error
            const error = new Error('Invalid credentials');
            auth.login.mockRejectedValue(error);

            // Define test credentials
            const credentials = {
                mail: 'test@test.com',
                password: 'wrong',
            };

            // Define the expected action to be dispatched when there is an error.
            const expectedAction = [
                { type: 'AUTH_LOGIN_REQUEST' },
                { type: 'AUTH_LOGIN_FAILURE', payload: error, error: true },
            ];

            // Dispatch the async action and wait for it to be rejected.
            await expect(
                authLogin(credentials)(dispatch, getState, {
                    service: { auth },
                    router,
                })
            ).rejects.toThrow(error);

            // Check that the actions dispatched are as expected and that the error is thrown.
            expect(dispatch).toHaveBeenCalledTimes(2);
            expect(dispatch).toHaveBeenNthCalledWith(1, expectedAction[0]);
            expect(dispatch).toHaveBeenNthCalledWith(2, expectedAction[1]);
        });
    });

    describe('Testing React Redux SYNC action "advertLoadedSuccess "', () => {
        const testadvertLoadedSuccess = { id: '1', title: 'Advert 1' };

        // test the action creator
        test('advertLoadedSuccess returns an action with type ADVERT_LOADED_SUCCESS and payload mockAdvert', () => {
            // call the action creator with the mock advert
            const action = advertLoadedSuccess(testadvertLoadedSuccess);

            // define the expected action object
            const expectedAction = {
                type: 'ADVERT_LOADED_SUCCESS',
                payload: testadvertLoadedSuccess,
            };

            // check that the action is equal to the expected action
            expect(action).toEqual(expectedAction);
        });
    });
});
